apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.name" . }}-app-config
  labels:
    app: {{ include "chart.name" . }}
data:
{{ (tpl (.Files.Glob "configs/config.json").AsConfig . ) | indent 2 }}