apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.name" . }}-ibpconnprofile-secret
  labels:
    app: {{ include "chart.name" . }}
data:
{{ (tpl (.Files.Glob "configs/profile.json").AsSecrets . ) | indent 2 }}
