kind: Secret
apiVersion: v1
metadata:
  name: {{ template "chart.fullname" . }}-secret
type: Opaque
data:
{{- if .Values.config.appId.tenantId }}
  APP_ID_TENANT_ID: {{ required "A valid .Values.config.appId.tenantId entry required!" .Values.config.appId.tenantId | b64enc | quote }}
{{- end }}
{{- if .Values.config.appId.clientId }}
  APP_ID_CLIENT_ID: {{ required "A valid .Values.config.appId.clientId entry required!" .Values.config.appId.clientId | b64enc | quote }}
{{- end }}
{{- if .Values.config.appId.clientSecret }}
  APP_ID_SECRET: {{ required "A valid .Values.config.appId.clientSecret entry required!" .Values.config.appId.clientSecret | b64enc | quote }}
{{- end }}
{{- if .Values.config.appId.iamKey }}
  APP_ID_IAM_KEY: {{ required "A valid .Values.config.appId.iamKey entry required!" .Values.config.appId.iamKey | b64enc | quote }}
{{- end }}
{{- if .Values.config.blockchain.adminSecret }}
  BC_ADMIN_SECRET: {{ required "A valid .Values.config.blockchain.adminSecret entry required!" .Values.config.blockchain.adminSecret | b64enc | quote }}
{{- end }}
{{- if .Values.config.keyProtect.iamKey }}
  KEYPROTECT_SERVICE_API_KEY: {{ required "A valid .Values.config.keyProtect.iamKey entry required!" .Values.config.keyProtect.iamKey | b64enc | quote }}
{{- end }}
  NEW_RELIC_LICENSE_KEY: {{ .Values.newRelic.licenseKey | b64enc | quote }}
{{- if .Values.config.database.password }}
  CLOUDANT_PASSWORD: {{ .Values.config.database.password | b64enc | quote }}
{{- end }}
{{- if .Values.config.cryptography.secretkey }}
  CRYPTO_SECRET_KEY: {{ .Values.config.cryptography.secretkey | b64enc | quote }}
{{- end }}
{{- if .Values.config.cryptography.salt }}
  CRYPTO_SALT: {{ .Values.config.cryptography.salt | b64enc | quote }}
{{- end }}
{{- if .Values.config.cryptography.iv }}
  CRYPTO_IV: {{ .Values.config.cryptography.iv | b64enc | quote }}
{{- end }}